# Generated by Django 4.0.6 on 2022-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidate/images'),
        ),
    ]
