# Generated by Django 4.0.6 on 2022-07-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_candidate_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='user_id',
        ),
    ]
