# Generated by Django 4.0.6 on 2022-07-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='candidate_id',
        ),
    ]
