# Generated by Django 4.0.6 on 2022-07-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_response_candidate_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
