# Generated by Django 4.0.6 on 2022-07-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_user_id_candidate_user_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response',
            new_name='candidate_response',
        ),
    ]
