# Generated by Django 4.0.6 on 2022-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='candidate_score',
            field=models.PositiveIntegerField(),
        ),
    ]
