# Generated by Django 4.0.6 on 2022-07-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_score_candidate_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='CandidateResponse',
        ),
    ]
