# Generated by Django 4.0.6 on 2022-07-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_and_options', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
