# Generated by Django 4.0.6 on 2022-07-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_and_options', '0003_alter_option_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank='True', upload_to='questions/images'),
        ),
    ]
